### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by maboiteaspam** [jasonsjones/stack-lifo#1]
Hi,

small typo in the README

``` js
var Stack = require('stack-lifo');
var stack - new Stack();
```

should be 

``` js
var Stack = require('stack-lifo');
var stack = new Stack();
```

**Comment by jasonsjones** [comment]
Good catch, thanks!  Fixed.  :+1: 

Actually, it was just a test to see if anyone actually looked at any of the repos :-)
